name: "JavaDocs"

on:
  push:
    branches: [ master ]
    paths: [ '**.java' ]

jobs:
  generate-javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Remove git
        run: rm -rf .git

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build docs with Maven
        run: mvn javadoc:javadoc

      - name: Remove docs folder
        run: rm -rf ./newdocs

      - name: Create docs folder
        run: mkdir docs newdocs/main newdocs/client docs/server

      - name: Copy main docs
        run: cp target/site/apidocs/. docs/main

      - name: Copy client docs
        run: cp nimspiel-client/target/site/apidocs/. docs/client

      - name: Copy server docs
        run: cp nimspiel-server/target/site/apidocs/. docs/server

      - name: Checkout gh-pages Pt. 1
        run: mkdir gh-pages && cd gh-pages

      - name: Checkout gh-pages Pt. 2
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Commit documentation changes
        run: |
            rm -rf docs
            cp ../docs .
            git config --global user.name 'Kilian Friedrich'
            git config --global user.email 'kilianfriedrich@users.noreply.github.com'
            git add -A
            git commit -am "Documention Update"
            git push