name: "JavaDocs"

on:
  push:
    branches: [ master ]

jobs:
  generate-javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build docs with Maven
        run: mvn javadoc:javadoc

      - name: Remove existing docs folder
        run: rm -rf ./docs

      - name: Create docs folder
        run: mkdir docs docs/main docs/client docs/server

      - name: Copy main docs
        run: test -e target/site/apidocs && cp target/site/apidocs docs/main
        continue-on-error: true

      - name: Copy client docs
        run: test -e nimspiel-client/target/site/apidocs && cp nimspiel-client/target/site/apidocs docs/client
        continue-on-error: true

      - name: Copy server docs
        run: test -e nimspiel-server/target/site/apidocs && cp nimspiel-server/target/site/apidocs docs/server
        continue-on-error: true

      - name: Clear everything else
        run: ls -A | grep -v docs | xargs rm -rf

      - name: Checkout gh-pages Pt. 1
        run: mkdir gh-pages && cd gh-pages

      - name: Checkout gh-pages Pt. 2
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Commit documentation changes
        run: |
            rm -rf docs
            cp ../docs .
            git config --global user.name 'Kilian Friedrich'
            git config --global user.email 'kilianfriedrich@users.noreply.github.com'
            git add -A
            git commit -am "Documention Update"
            git push